version: "3"

services:
  squid-proxy:
    image: ubuntu/squid
    container_name: squid-proxy
    tty: true
    ports:
      - 3128:3128
    volumes:
      - ./config/squid/squid-1.conf:/etc/squid/squid.conf

