version: "3"

services:
  php-80:
    volumes:
      - ${PROJECT_PATH}/practice-app:/var/www/html/practice-app
  nginx:
    volumes:
      - ${PROJECT_PATH}/practice-app:/var/www/html/practice-app
      - ./config/nginx/practice-app.conf:/etc/nginx/conf.d/practice-app.conf
