version: '3.7'
services:
  es01:
    container_name: es01
    image: elasticsearch:8.4.1
    restart: always
    environment:
      - node.name=es01
      - ES_SKIP_SET_KERNEL_PARAMETERS=${ES_SKIP_SET_KERNEL_PARAMETERS}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch/es.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/es-01/data:/usr/share/elasticsearch/data
      - ./data/es-01/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    networks:
      - backend

  es02:
    container_name: es02
    image: elasticsearch:8.4.1
    restart: always
    environment:
      - node.name=es02
      - ES_SKIP_SET_KERNEL_PARAMETERS=${ES_SKIP_SET_KERNEL_PARAMETERS}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch/es.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/es-02/data:/usr/share/elasticsearch/data
      - ./data/es-02/logs:/usr/share/elasticsearch/logs
    ports:
      - 9201:9200
    networks:
      - backend

  es03:
    container_name: es03
    image: elasticsearch:8.4.1
    restart: always
    environment:
      - node.name=es03
      - ES_SKIP_SET_KERNEL_PARAMETERS=${ES_SKIP_SET_KERNEL_PARAMETERS}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch/es.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/es-03/data:/usr/share/elasticsearch/data
      - ./data/es-03/logs:/usr/share/elasticsearch/logs
    ports:
      - 9202:9200
    networks:
      - backend

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.4.1
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://es01:9200
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    links:
      - es01
    depends_on:
      - es01
    networks:
      - backend

