version: "3"

networks:
  backend:
    driver: bridge


services:

  mysql:
    image: library/mysql:8.0
    ports:
      - 3306:3306
    networks:
      - backend
    volumes:
      - ./data/mysql-80:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
