version: "3"

services:
  php-80:
    volumes:
      - ${PROJECT_PATH}/practice-app:/usr/share/nginx/html/practice-app
  nginx:
    volumes:
      - ${PROJECT_PATH}/practice-app:/usr/share/nginx/html/practice-app
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
