cluster.name: es-cluster

bootstrap.memory_lock: true

network.host: 0.0.0.0
http.host: 0.0.0.0

transport.port: 9300

# setting connection node
discovery.seed_hosts: ["es01","es02", "es03"]

node.roles: [master,data,ingest,remote_cluster_client]

xpack.security.enabled: false
xpack.watcher.enabled: true

# kibana setting
xpack.monitoring.templates.enabled: true
xpack.monitoring.collection.enabled: true


http.cors.enabled: true
http.cors.allow-origin: "*"

# close folder protection
cluster.routing.allocation.disk.threshold_enabled: false

cluster.initial_master_nodes: ["es01","es02","es03"]
